version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
      - 5432:5432

  app:
    build: .
    command: ["./wait-for-it.sh", "postgres:5432", "--", "go", "run", "main.go"]
    volumes:
      - .:/go/src/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
  g